import assert from 'node:assert'
import { parse } from './parse.ts'
let p = parse('Running 40 tests using 4 workers\n  ✓  [chromium] › a.spec.ts:3 ok (1s)\n[12/40] [chromium] › b.spec.ts\n')
assert.equal(p.done, 12); assert.equal(p.total, 40)
p = parse('scanning\nPROGRESS 3/10 altaria_back.jpg\nmeasured 2/3 corners\n')
assert.equal(p.done, 3); assert.equal(p.total, 10)
p = parse(' Test Files  2 failed | 10 passed (12)\n      Tests  3 failed | 88 passed (91)\n')
assert.equal(p.passed, 88); assert.equal(p.failed, 3)
p = parse('Failed!  - Failed:     1, Passed:    41, Skipped:     0, Total:    42\n')
assert.equal(p.passed, 41); assert.equal(p.failed, 1)
p = parse('Evaluating scenarios 45%\r Evaluating scenarios 60%')
assert.equal(p.pct, 60); assert.equal(p.last, 'Evaluating scenarios 60%')
p = parse('log at 2026/10/04 12:00\n')
assert.equal(p.total, undefined)
p = parse('........................................ [ 22%]\n....................................... [ 45%]\n')
assert.equal(p.pct, 45)
// Your projects' output (real lines from past runs).
p = parse('shadblur: 0 bad/wrong lines; last: ramp 225 0.85 failed\natk4: 0 bad/wrong lines; last: yellow err None failed CARD_NOT_FOUND\n')
assert.equal(p.failed, undefined)
p = parse('PPG attempt 1 failed: failed (\nPPG done (attempt 2)\nPPTRH attempt 2 failed: failed (429\n')
assert.equal(p.failed, undefined)
p = parse("    MCAP 2374 | 096/182 | Team Rocket's Tyranitar (Prerelease)\n")
assert.equal(p.total, undefined)
p = parse('PROGRESS 4/18 bordered/pansage-par-004-back.jpg ok  54/46 52/48\nmeasured 42/58\n')
assert.equal(p.done, 4); assert.equal(p.total, 18)
p = parse('  Attack Resolution: 1/1 passed\n  Timing Questions: 2/3 passed\n\nResult: 13/20 scenarios fully passed all applicable criteria.\n')
assert.equal(p.passed, 13); assert.equal(p.failed, 7)
p = parse('shadow-blur            93 cases  0 WRONG\nshadow-dirs           165 cases  2 WRONG\nsaved backend/.tuning/attacks/baseline\n')
assert.equal(p.passed, 256); assert.equal(p.failed, 2)
p = parse('================= 577 passed, 12 xfailed in 466.40s (0:07:46) =================\n')
assert.equal(p.passed, 577); assert.equal(p.failed, undefined)
p = parse('1 failed, 41 passed in 2.1s\n')
assert.equal(p.passed, 41); assert.equal(p.failed, 1)
p = parse('  2 failed\n    [chromium] › tests/e2e/role-removal.spec.ts:47:3\n  9 skipped\n  36 passed (5.1m)\n')
assert.equal(p.passed, 36); assert.equal(p.failed, 2)
console.log('parse checks ok')
